# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

# zsh plugins
source ~/git/zsh_plugins/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/git/zsh_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/git/zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

alias ls='ls --color=auto'
# Confirm before overwriting something
alias cp="cp -i"
# Show sizes in MB
alias free='free -m'

# Bind Suppr key to delete character instead of inserting ~
bindkey "^[[3~" delete-char

# Don't consider certain characters part of the word
WORDCHARS=${WORDCHARS//\/[&.;]}

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

zstyle ':completion:*' menu select
bindkey '^[[Z' reverse-menu-complete
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
# Case insensitive tab completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true                              # automatically find new executables in path


# delete previous word with ctrl+backspace
bindkey '^H' backward-kill-word
# Don't save commands that start with space
setopt histignorespace

