# use antidote to handle all plugins
source ~/.antidote/antidote.zsh
antidote load < ~/.zsh_plugins.txt

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
  compinit -C    # use cache if less than 24h old
else
  compinit
fi

# End of lines added by compinstall

# zsh plugins
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias ls='ls --color=auto'
# Confirm before overwriting something
alias cp="cp -i"
# Show sizes in MB
alias free='free -m'

# Bind Suppr key to delete character instead of inserting ~
bindkey "^[[3~" delete-char

# Don't consider certain characters part of the word
WORDCHARS=${WORDCHARS//\/[&.;]}

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

zstyle ':completion:*' menu select
bindkey '^[[Z' reverse-menu-complete
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
# Case insensitive tab completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true                              # automatically find new executables in path

# delete previous word with ctrl+backspace
bindkey '^H' backward-kill-word

# Home and End key binding
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line

# History config
setopt hist_ignore_dups     # no duplicates
setopt hist_ignore_space    # ignore commands starting with space
# setopt share_history        # share history across sessions

